### ISSUE TITLE
Send users their results with obscuration of un-voted rounds

### ISSUE THREAD

**Issue by darrenwee** [louietyj/tinder-turing#16]
User types `/report` at any point and receives the following message:

```
Round 1: Bot (100)
Round 2: VOTE FIRST!!!
Round 3: Charlie (67)
Round 4: Bot (13)
Round 5: VOTE FIRST!!!
```

Round 2 and 5 are obscured because the user has not registered their confidence for that round.

**Comment by louietyj** [comment]
Cannot, they can change their confidence at any time.

We should implement this as a function that only we can run, to send them their report. We only run this command at the end of the activity.

**Comment by louietyj** [comment]
I think this is low-pri since we can just take a screenshot of the pairing and post it on Slack afterwards haha. They'll be curious to look at everyone else's pairings and confidences too.
